//messing around with enum
public enum Cards {
    RIGHT_LEG, LEFT_LEG, RIGHT_ARM, LEFT_ARM, FORBIDDEN_ONE, BLUE_EYES, 
    WHITE_STONE, LIBRARY, TOON_DRA, UPSTART, TOON_TABLE, TERRAFORMING, 
    DEALINGS, TRADE_IN, CARDS_OF_CONSONANCE, VOID, POT, ONE_DAY, 
    PSUEDO_SPACE, CHICKEN_GAME;
}